name: CMake/Xcode

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15]
        build-type: [Release, Debug]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan package manager
      shell: bash
      run: sudo pip3 install conan

    - name: Check Conan version
      shell: bash
      run: conan --version

    - name: Create Build Environment
      run: mkdir ${{github.workspace}}/build-${{ matrix.build-type }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      run: cmake $GITHUB_WORKSPACE -GXcode

    - name: Build
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: cmake --build . --config ${{ matrix.build-type }}

    - name: Test
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: ctest -V -C ${{ matrix.build-type }}
