name: CMake/Visual Studio 16

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019]
        build-type: [Release, Debug]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan package manager
      shell: bash
      run: pip install conan

    - name: Check Conan version
      shell: bash
      run: conan --version

    - name: Create Build Environment
      run: mkdir ${{github.workspace}}/build-${{ matrix.build-type }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      run: cmake $GITHUB_WORKSPACE -G"Visual Studio 16 2019"

    - name: Build
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: ctest -V -C Debug
